
title: Spirent iTest Developer Community # your title
url: 'https://clarkwhitty.github.io/apt'
baseurl: '/' #change it according to your repository name



# Profile information
yourname: Spirent APT B.U.  ## put your name
location: San Jose, CA


## Social Profiles
facebook: http://www.facebook.com  ## your facebook account url
twitter: http://www.twitter.com  ## your twitter account url
linkedin: http://www.linkedin.com  ## your linkedin account url
dribbble: http://www.dribble.com  ## you dribbble account url
foursquare: http://www.foursquare.com  ## your foursquare account url



# Update all the sections by editing the files inside _includes folder.
